[tools]
go = "latest"
node = "latest"
"npm:@tailwindcss/cli" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:sql-formatter" = "latest"
"npm:tailwindcss" = "latest"
"npm:vscode-langservers-extracted" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
