theme = "signal"

[editor]
true-color = true
cursorline = true
bufferline = "always"
# auto-completion = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "‚ñè"
skip-levels = 1

[editor.lsp]
auto-signature-help = false
display-color-swatches = false

[editor.file-picker]
hidden = false

[keys.normal]
"C-w" = ":buffer-close"

"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

"ret" = ":write"

[keys.normal.space]
q = ":quit"
l = ":reload-all"
t = ":open ~/todo.txt"

[keys.insert]
"C-[" = "normal_mode"
"C-k" = "signature_help"
"C- " = "completion"

[keys.select]
"C-[" = "normal_mode"
